### ISSUE TITLE
Renaming effects - alignment

### ISSUE THREAD

**Issue by bartlannoeye** [FormsCommunityToolkit/FormsCommunityToolkit#19]
_From @Depechie on February 16, 2017 7:15_

We are looking to rename the current effects, to streamline the naming.
But we are a bit stuck with the current proposal!

Proposal:
Current name : public class CapitalizeKeyboardEffect : RoutingEffect
New name : public class EntryCapitalizeKeyboard : RoutingEffect
So prefix the control it targets and loose the suffix Effect

But if we uphold this, we get in trouble with the static classes that are needed for adding dependency properties to pass through to the actual RoutingEffect.

Problem:
public static class ChangeColorEffect with tandem class > public class ChangeColorSwitchEffect : RoutingEffect ( https://github.com/FormsCommunityToolkit/Effects/blob/dev/src/Effects/ChangeColorEffect.cs )
public static class ChangePickerColorEffect with tandem class > public class ChangeColorPickerEffect : RoutingEffect ( https://github.com/FormsCommunityToolkit/Effects/blob/dev/src/Effects/ChangePickerColorEffect.cs )

How do we rename these? ChangeColorEffect would become SwitchChangeColor, but what would ChangeColorSwitchEffect be then?
Same with the picker class...

Suggestions?

_Copied from original issue: FormsCommunityToolkit/Effects#48_

**Comment by bartlannoeye** [comment]
_From @jamesmontemagno on February 16, 2017 14:8_

I think we should just follow the documentation perhaps?

https://developer.xamarin.com/guides/xamarin-forms/effects/passing-parameters/attached-properties/

So:
* CapitalizeKeyboardEffect
* EntryCapitalizeKeyboardEffect : RoutingEffect
* EntryCapitalizeKeyboardEffect  : PlatformEffect

I think looking at the docs we just keep the Effect at the end. I think it is okay.

**Comment by bartlannoeye** [comment]
_From @Depechie on February 16, 2017 14:13_

That is a good suggestion indeed, but not enough in our scenario!
Problem lies also in the fact that we created 2 change color effects! One for a switch and one for a picker.
So if we follow the ruling both current static classes for the attached properties wouldget the same name, BUT with different properties :/

So we need to do something about that too.

**Comment by bartlannoeye** [comment]
_From @jamesmontemagno on February 16, 2017 14:14_

Ahhhhhh I see now. Interesting.

**Comment by bartlannoeye** [comment]
_From @jamesmontemagno on February 16, 2017 14:15_

Soooooo

* SwitchChangeColor
* SwitchChangeColorEffect : RoutingEffect
* SwitchChangeColorEffect : PlatformEffect

How is that?

**Comment by bartlannoeye** [comment]
_From @Depechie on February 16, 2017 14:24_

I like this!

**Comment by bartlannoeye** [comment]
_From @jamesmontemagno on February 16, 2017 14:29_

Do it! I think we need to do it in the main line though.

**Comment by bartlannoeye** [comment]
_From @Depechie on February 16, 2017 14:32_

Yep... will look at it this week!

**Comment by Depechie** [comment]
@jamesmontemagno ok sorry doing the renaming made me realize something else that we need to double check!
So latest renaming example was given like this:

- SwitchChangeColor
- SwitchChangeColorEffect : RoutingEffect
- SwitchChangeColorEffect : PlatformEffect

Meaning when there is a static class we drop the effect suffix. But keep the suffix for Routing / Platform effect classes.
But this has a negative ( in my opinion ;) ) side effect in usage in XAML!
Meaning for a normal effect we would be writing:

```
<Entry.Effects>
   <effects:EntryCapitalizeKeyboardEffect />
</Entry.Effects>
```

But for one with a static class this would become:
```
<Switch x:Name="ChangeColorSwitch" effects:SwitchChangeColor.FalseColor
```

So a difference in writing in XAML, with and without suffix...
Is this an issues or not?

**Comment by jamesmontemagno** [comment]
I think that dropping the name would cause issues correct? as the names of the classes would be the same?

**Comment by Depechie** [comment]
Yes, so I would suggest only dropping them for the effects that have NO static class.
Problem with this thought, is that Devs would need to understand the reason behind it and not forget it when creating new effects...
So other solution is just keeping as mentioned above and live with the writing difference in Xaml for regular effects versus those with static class ( guess this is not that big of a deal ;) )

**Comment by bartlannoeye** [comment]
We can write the reason for the 'weird naming behavior' in our guidelines for creating effects. So don't think that is an issue.
