### ISSUE TITLE
Customize the Xamarin.Forms.Entry Keyboard Return Button

### ISSUE THREAD

**Issue by brminnick** [FormsCommunityToolkit/FormsCommunityToolkit#20]
## Feature Request

Modify the `Xamarin.Forms.Entry` Keyboard Return Button

To see the full write-up, click here:
https://github.com/brminnick/EntryCustomReturnPlugin

This Effect allows the user to customize the Keyboard Return Button. It includes a Bindable `ReturnType` Property to set the Keyboard Return Type using the native implementations and a Bindable `Command` Property to trigger a Command when the Return Button is tapped.

```
public enum ReturnType
{
	Default,
	Done,
        Go,
	Next,
	Search,
	Send,
}
```

**Comment by brminnick** [comment]
No feedback

**Comment by Depechie** [comment]
@brminnick ok this is an oversight from our part and I want to say I'm very sorry!
Somehow this request slipped my mind and I forgot to address it...
Thanks anyway to open source your solution on Github so other people can benefit.
It seems you guys went ahead with using an effect, if you still feel up to it a PR to integrate it in this repo would be great. But I can understand if that is no longer what you would like to do.

Again sorry for the bad communication and attention from our side.
