### ISSUE TITLE
Unable to add Effects NuGet to UWP head

### ISSUE THREAD

**Issue by davidortinau** [FormsCommunityToolkit/FormsCommunityToolkit#22]
## Bug 
When trying to add the Effects NuGet to my UWP head project, it fails with the errors below.

Version Number of Plugin: 1.0.0.49-beta
Device Tested On: 
Simulator Tested On:

### Expected Behavior
The NuGet installs without error.

### Actual Behavior
iOS and Android installs fine, but UWP fails with the errors below.

### Steps to reproduce the Behavior
Attempt to add this package to a UWP project.

Here's my repo: https://github.com/davidortinau/xamarin-blog-samples/tree/master/xamarin.forms/RegistrationForm 

FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
FormsCommunityToolkit.Effects 1.0.0.49-beta is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).

**Comment by bartlannoeye** [comment]
Published latest beta packages to https://www.myget.org/F/formscommunitytoolkit/api/v3/index.json
