### ISSUE TITLE
Adding Binding to TextColor or Text on label using CustomFontEffect breaks on iOS

### ISSUE THREAD

**Issue by mikescott8** [FormsCommunityToolkit/FormsCommunityToolkit#25]
Creating on the right repo this time (sorry about that)

### NOTES:
**- Only on iOS**
**- note sure if this is issue with the effect or the way effects are implemented in Xamarin**

## Bug 
Binding TextColor or Text on a label that is using the effect causes the label to not display the custom font anymore.

Version Number of Plugin: 
Device Tested On: ipad mini (>10.0)
Simulator Tested On: iOS (10.2)

### Expected Behavior
if I bind TextColor the label should display in said color on change

### Actual Behavior
if I bind TextColor the label loses CutomFontEffect

### Steps to reproduce the Behavior
The sample below shows the issue with binding TextColor but it also breaks if you bind Text on a label using the effect.

Medium and BodyDarkTextColor are app resource dictionary items.
StatusIndicatorTextColor is ViewModel property of type Color

```
<Label x:Name="StatusIndicatorWorks" 
                                    Text="1a> &#xf054;"
                                    VerticalOptions="Center" 
                                    VerticalTextAlignment="Center" 
                                    FontSize="{StaticResource Medium}"
                                    TextColor="{DynamicResource BodyDarkTextColor}"
                                    >
    <Label.Effects>
        <effects:CustomFontEffect FontPath="fontawesome-webfont.ttf" FontFamilyName="FontAwesome"/>
    </Label.Effects>
</Label>
<Label x:Name="StatusIndicatorBreaks" 
                                    Text="1b> &#xf054;"
                                    VerticalOptions="Center" 
                                    VerticalTextAlignment="Center" 
                                    FontSize="{StaticResource Medium}"
                                    TextColor="{Binding StatusIndicatorTextColor}"
                                    >
    <Label.Effects>
        <effects:CustomFontEffect FontPath="fontawesome-webfont.ttf" FontFamilyName="FontAwesome"/>
    </Label.Effects>
</Label>
<Label x:Name="StatusIndicatorWorksWithoutEffect" 
                                    Text="2> &#xf054;"
                                    VerticalOptions="Center" 
                                    VerticalTextAlignment="Center" 
                                    FontSize="{StaticResource Medium}"
                                    TextColor="{Binding StatusIndicatorTextColor}"
                                    >
</Label>
```

![effectissue](https://cloud.githubusercontent.com/assets/1325022/23615649/59005b9e-0244-11e7-9e1c-428c30ea5438.PNG)

**Comment by mikescott8** [comment]
I don't have Git installed on client provided PC so hope this zip is ok.

But this is simple solution showing the bug on iOS. Run the app on iOS and click the "change" button to change the text for the first of the three labels on the form. Works on Android.

[FontEffectBugDemo.zip](https://github.com/FormsCommunityToolkit/FormsCommunityToolkit/files/863109/FontEffectBugDemo.zip)

**Comment by Depechie** [comment]
Thx @mikescott8 ! Think @jfversluis is going to look at it...

**Comment by jfversluis** [comment]
I'll see if I can look into this weekend!

**Comment by mikescott8** [comment]
Thanks for fixing this...well working around the Xamarin bug. 😃

**Comment by jfversluis** [comment]
No problem! Let me know if there is anything else I can help with 👍
