### ISSUE TITLE
Behaviors repo

### ISSUE THREAD

**Issue by akamud** [FormsCommunityToolkit/FormsCommunityToolkit#26]
I remember there was a Behavior repo a few days ago, what happened to it? Do you still plan on having a Behavior repo we can contribute to?

**Comment by bartlannoeye** [comment]
We merged all repos into this repo, you can find the source code for the behaviours under https://github.com/FormsCommunityToolkit/FormsCommunityToolkit/tree/dev/src/Behaviors

**Comment by akamud** [comment]
Searching on NuGet I can only see the Effects and Controls packages. How are the behaviors being distributed?

**Comment by bartlannoeye** [comment]
You can get pre-release packages from https://www.myget.org/F/formscommunitytoolkit/api/v3/index.json for now. We'll try to get a package on NuGet one of these days as well.

**Comment by bartlannoeye** [comment]
@akamud the behavior package is on NuGet as well
