### ISSUE TITLE
Switch don't raise event Toggled

### ISSUE THREAD

**Issue by Depechie** [FormsCommunityToolkit/FormsCommunityToolkit#31]
_From @xamarindevelopervietnam on April 18, 2017 15:16_

If you set FalseColor and TrueColor of Swich, it won't raise event Toggled or change IsToggle property

## Bug 

Version Number of Plugin: FormsCommunityToolkit.Effects.1.0.0.49-beta
Device Tested On: HTC One M9 (Android 6.0)
Simulator Tested On:

## Feature Request:
Please fill in what you would like

_Copied from original issue: FormsCommunityToolkit/Effects#50_

**Comment by Depechie** [comment]
Good catch! Will try to fix this...

**Comment by xamarindevelopervietnam** [comment]
Cheers!
