### ISSUE TITLE
How to contribute to documentation

### ISSUE THREAD

**Issue by akamud** [FormsCommunityToolkit/FormsCommunityToolkit#33]
I see we are missing documentation, I believe this is very important for people to use a project, I'm wondering, how can we help with the documentation? Do we have a guideline that we want to follow? What should we know before we start writing docs for the project?

**Comment by bartlannoeye** [comment]
Hey @akamud, we did an initial start on getting our documentation on http://formscommunitytoolkit.readthedocs.io/en/latest/ which parses all md files from the /docs folder and generates a nice html website that's searchable. Right now there's only an initial structure set up, with a single page being [CapitalizeKeyboard](http://formscommunitytoolkit.readthedocs.io/en/latest/Effects/Entry/CapitalizeKeyboard/) as an example. I think we should continue in that direction. It's quite similar to the [UWP Community Toolkit documentation](http://docs.uwpcommunitytoolkit.com/en/master/animations/Blur/).

So as long as you stick to that structure, any help is welcome!

_I'm also working on merging the multiple sample applications from all the old repositories in something that both shows how to use the code, but also can be used as a reference. Again in line with the UWP toolkit. There's still some work there on my part._

**Comment by akamud** [comment]
Awesome. Do you think we could add this to Contributing.md? To help reduce friction for new contributors?

**Comment by jsuarezruiz** [comment]
@bartlannoeye I love the idea. We will continue to increase documentation.

**Comment by bartlannoeye** [comment]
This is already described on Contributing.md under "[A good pull request](https://github.com/FormsCommunityToolkit/FormsCommunityToolkit/blob/dev/Contributing.md#a-good-pull-request)".

I've added a link to the readme as well.
