### ISSUE TITLE
error: System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by maxdiable** [FormsCommunityToolkit/FormsCommunityToolkit#35]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:1.0.0.49-beta
Device Tested On:LG
Simulator Tested On:

hi, i tested switch on my xamarin forms, but my debug show this error in main activity:
LoadApplication (new PayAndShare.App ());

this is my page:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:effects="clr-namespace:FormsCommunityToolkit.Effects;assembly=FormsCommunityToolkit.Effects"
             x:Class="PayAndShare.Views.Page1">

    <StackLayout Padding="20">
        <Label Text="Regular switch" />
        <Switch x:Name="NormalSwitch" />
        <Label Text="ChangeColorSwitchEffect" Margin="0,20,0,0" />
        <Switch x:Name="ChangeColorSwitch" effects:ChangeColorEffect.FalseColor="#AAEE00" effects:ChangeColorEffect.TrueColor="Blue" />
    </StackLayout>

</ContentPage>

any help?
br
Massimo

**Comment by Depechie** [comment]
@maxdiable can you see if the changing the name fixes this? The effect has been renamed and the old example does not yet reflect this... so the name now is SwitchChangeColor

Can't test myself at the moment, so please let me know if this works or not. If not I'll make some more time to be able to test run this myself!

**Comment by Depechie** [comment]
Ow I think we may have a bug if I look at the effect code, the BindableProperties on the SwitchChangeColor static class should be of typeof(Color) instead of typeof(Color?)

I'll change that in another PR soon...

**Comment by maxdiable** [comment]
hi,
Thanks, thank you for the answer, but there is no documentation or examples? 
Yours sincerely
Max

**Comment by Depechie** [comment]
True... :/
We are currently in the process to bring over the samples app again.
When that is done we will tackle the documentation!

**Comment by maxdiable** [comment]
hi,
Thanks, thank you for the answer.
Could i know when the new version will be ready?
Yours sincerely
Max

**Comment by Depechie** [comment]
I'll try to keep you posted through this issue...

**Comment by maxdiable** [comment]
Thanks :)
good woork :)

**Comment by Depechie** [comment]
@maxdiable the fix is in the PR https://github.com/FormsCommunityToolkit/FormsCommunityToolkit/issues/36 also in there is a samples page with the correct syntax for using the switch effect.
I think as long as the PR is still open, the nuget will not be correct.

**Comment by Depechie** [comment]
If you just want to use the nuget, yeah... the PR first needs to be merger into the main code - that will trigger a new nuget creation.
But if you like you could also just copy paste the effect from the PR if needed :)

**Comment by maxdiable** [comment]
Ok, I expect there is the new version on nuget..I hope it will be released soon :)
good job :)
br
Max
