### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by maxdiable** [FormsCommunityToolkit/FormsCommunityToolkit#41]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.0.0.49-beta
Device Tested On: LG
Simulator Tested On:

hi, i see your samples but i not find "SwitchChangeColor" in effects
br
Max

**Comment by Depechie** [comment]
Hey Max, what is it you are missing?
https://github.com/FormsCommunityToolkit/FormsCommunityToolkit/blob/dev/src/Effects/Effects.Android/Effects/Switch/SwitchChangeColor.cs

**Comment by maxdiable** [comment]
Sorry, I saw new examples and I thought I had put the new version on nuget
br
Max

**Comment by bartlannoeye** [comment]
SwitchChangeColor is on NuGet in https://www.nuget.org/packages/FormsCommunityToolkit.Effects/1.0.0.110-beta
