### ISSUE TITLE
DisableAutoCorrectEffect & CapitalizeKeyboardEffect do nothing when used on Entry (iOS)

### ISSUE THREAD

**Issue by dfoulk** [FormsCommunityToolkit/FormsCommunityToolkit#46]
## Bug 

Version Number of Plugin: 1.0.0.49-beta
Device Tested On:
Simulator Tested On: iPhone 7 iOS 10.3

### Expected Behavior
I expected the following code to enable all caps on the keyboard AND disable spell-checking/auto-correction.

    ...
    xmlns:fcteffects="clr-namespace:FormsCommunityToolkit.Effects;assembly=FormsCommunityToolkit.Effects"
    ...
    <Entry Text="{Binding Aircraft.TailNumber}">
        <Entry.Effects>
            <effects:DisableAutoCorrectEffect />
            <effects:CapitalizeKeyboardEffect />
        </Entry.Effects>
    </Entry>

### Actual Behavior
The entry acts as though neither effect is applied to it.

### Steps to reproduce the Behavior
1) Install FormsCommunityToolkit.Effects (1.0.0.49-beta) from NuGet
2) Add 'xmlns' attribute for 'FormsCommunityToolkit.Effects' to your XAML file
3) Add the effect(s) to an `<Entry />`
    a) I created x4 `<Entry />` elements with all possible combinations of the effects (without effects, with 'DisableAutoCorrectEffect', with 'CapitalizeKeyboardEffect', with both effects)
4) Deploy the app to an iOS 10.3 simulator
5) Test the effects by typing in the '<Entry />' elements
    a) I used the simulator's (virtual) keyboard (not the optional hardware keyboard)

These effects are really the only thing I was after in this library. I tried to fix the issue, but I couldn't figure it out. Anyone know how to resolve this? Thanks

**Comment by dfoulk** [comment]
So the issue is that the effects are not attaching... I think that the names in **src/Effects/Effects/EffectIds.cs**, **src/Effects/Effects/Entry/EntryCapitializeKeyboard.cs**, **src/Effects/Effects.iOS/Effects/Entry/EntryCapitalizeKeyboard.cs** are not matching, thus the effect's "routing name" is not resolving properly...

**Comment by Depechie** [comment]
@dfoulk thanks for bringing this up! We'll need to investigate further to see what could cause this...

**Comment by dfoulk** [comment]
Thank you! I will try to dig a little more this week and see what I can find...

**Comment by Xaniith** [comment]
Hi @dfoulk I'm not sure if you're still looking to have the problem solved but I do believe you're correct in the incorrect naming.
The docs describe using the suffix 'Effect' such as


```csharp
    MyEntry.Effects.Add(Effect.Resolve("FormsCommunityToolkit.Effects.CapitalizeKeyboardEffect"));
```

I ran into the issue of it not working as well (although on Android) but it worked with


```csharp

    MyEntry.Effects.Add(Effect.Resolve("FormsCommunityToolkit.Effects.EntryCapitalizeKeyboard"));

```

The same thing happened when testing in XAML, changing 

```xml

     <Entry.Effects>
          <effects:DisableAutoCorrectEffect />
          <effects:CapitalizeKeyboardEffect />
      </Entry.Effects>
```
to

```xml

     <Entry.Effects>
          <effects:EntryDisableAutoCorrect />
          <effects:EntryCapitalizeKeyboard />
      </Entry.Effects>
```

**Comment by dfoulk** [comment]
I do still need this to be solved, yes. When things calm down here at the office, I will take a stab at fixing them. If anyone has the time to patch this (before then), we would be grateful!

**Comment by Depechie** [comment]
Sorry for the delay... just wanted todo a follow up.
When I test this in the sample app that is provided with the source here on github, I'm getting the correct results?
Did you also try that? Or only the nuget?

**Comment by Xaniith** [comment]
Hi @Depechie. Looking at the Samples code, they do have the names as (eg. DisableAutoCorrect)
```xml
<Entry.Effects>
    <effects:EntryDisableAutoCorrect />
</Entry.Effects>
````
Which is what I had, to make it work.

While the docs (and @dfoulk 's provided code) have 
```xml
<Entry.Effects>
        <effects:DisableAutoCorrectEffect />
</Entry.Effects>
````
Unless I'm missing something, it seems like there was a naming scheme change, and not _all_ mentions of these effects were changed

**Comment by Depechie** [comment]
Oooh ok I see, damn yeah updating the DOCS is still on the ToDo list :( sorry about that guys.
Going to close this issue... if there are other remarks still we can reopen it again if needed.

**Comment by dfoulk** [comment]
@Depechie - No worries bud, but can you tell me what I have wrong? Do I need to use `EntryDisableAutoCorrect` instead of `DisableAutoCorrectEffect`?

If so, what is the correct class for the capitalization?

Thanks in advance,
-Derek

**Comment by Depechie** [comment]
I tested with this code, see if that works
```
        <Entry Placeholder="start typing..." VerticalOptions="Start"
               Margin="0,10,0,10"
               Grid.Row="1">
            <Entry.Effects>
                <effects:EntryDisableAutoCorrect />
                <effects:EntryCapitalizeKeyboard />
            </Entry.Effects>
        </Entry>
```
