### ISSUE TITLE
Sample of LableSizeFontToFit

### ISSUE THREAD

**Issue by kmpm** [FormsCommunityToolkit/FormsCommunityToolkit#48]
## Feature Request:
I am trying to get LableSizeFontToFit working but without any luck. It would be great to have a working sample of how to use it since in this case it's probably my code that's the issue.

**Comment by Depechie** [comment]
You are right, seems we have not yet added the label samples.
Let us fix this and I'll come back on this issue...

**Comment by Depechie** [comment]
Hey @kmpm the sample is up on my fork of the project. I've requested a PR that is not yet merged, but you can already look at the code and download it if you want.
