### ISSUE TITLE
Please update Nuget Package

### ISSUE THREAD

**Issue by Hunv** [FormsCommunityToolkit/FormsCommunityToolkit#51]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Old version of Effects is online 

Version Number of Plugin: 1.0.0.49-beta
Device Tested On: Android
Simulator Tested On: Android

### Expected Behavior
SwitchChangeColor Effect works

### Actual Behavior
SwitchChangeColor Effect results in Unhandled Exception "Type SwitchChangeColor not found in xmlns clr-namespace:FormsCommunityToolkit.Effects;assembly=FormsCommunityToolkit.Effects"

### Steps to reproduce the Behavior
Use the Library from the Nuget Repo.
Issue described is already fixed (#35) but not in the Nuget.

## Feature Request:
Update the Nuget Repository.

**Comment by bartlannoeye** [comment]
Pushed https://www.nuget.org/packages/FormsCommunityToolkit.Effects/1.0.0.110-beta, will be available as soon as NuGet indexed it.
